### PR TITLE
Version1.2

### LINKED ISSUE #4: Calendar widget does not set the year properly
When using the calendar widget to set event times, the year is wrongly set as two digits. So if I set today's date (5/28/16) it will be interpreted by the events list as 5/28/1916

### PR DESCRIPTION
**Pull request by ighormartins**
This version improves the UI.
- It uses a new datetime-picker in order to fix #4 
- It's now possible to go back to the editor from the counter page by double-clicking the event name
- It's now possible to share the events by using an URL. We should think about building an API for this later.

Do we need to add anything else for the CodingNight2?

### CODE REVIEW

**Comment by ighormartins** [comment]
Would be nice if someone could update the README before merging this.

It should explain how to:
- Add a new event
- Start the counter
- Go back to editor
- Share the clock

**Comment by pangelo** [comment]
@ighormartins te new version looks great :)

I have fixed a small issue with the build and updated the README file with the info you suggested and a couple of new screenshots in my branch at 

https://github.com/pangelo/events-clock/tree/version1.2-fixes

Another issue I found was that the URL that can be shared from the app sends the receiver to the /set-events page where they can edit their own version of the events "playlist". For events like the Coding Night where the event list is preset, it would be nice that the shared URL sent the user directly to a "read only" version of the running timer. 

I also added a couple of issues with ideas for new app features.

**Comment by ighormartins** [comment]
Ok. Nice.
I just merged your commits, and I'll fix the redirect issue before merging this pull request into master.
Thanks.

**Comment by ighormartins** [comment]
I fixed the redirect, and opened an issue #16 to create the read-only sharing feature.

**Pull request merged**
